### ISSUE TITLE
is rbeapi necessary for netdev_stdlib_eos

### ISSUE THREAD

**Issue by greenpau** [arista-eosplus/rbeapi#1]
Ruby Client for eAPI is listed as a dependency for `netdev_stdlib_eos`:
https://forge.puppetlabs.com/aristanetworks/netdev_stdlib_eos#development

However, the same doc states that:
> Install the rbeapi gem on the switch See Ruby Client for eAPI

Is there a need to install rbeapi gem through `puppet`?

**Comment by privateip** [comment]
Apologizes for the confusion here, I will take an action to provider more clarity in the documentation.  Yes, the Ruby Client for eAPI (rbeapi gem) is required to run the netdev eos provider on the destination node

**Comment by greenpau** [comment]
@privateip , also, let's say you have the gem installed. How do you make it persistent or reboot-tolerate?

**Comment by jerearista** [comment]
Paul,
  Just wanted to ensure all of your questions were answered offline.

1. The Ruby Client for eAPI (rbeapi) rubygem should also be installed on the master due to the way puppet plugins are evaluated before pluginsync.  This also enables additional test scenarios.

2. To make the rbeapi rubygem install persistent on a node, the best option is to build/install rbeapi as a switch extension.  From the git source, update and run 'make rpm', copy to the switch, then use the following commands on the switch:

    Arista# extension [pe-]rbeapi....
    Arista# copy installed-extensions boot-extensions
