### ISSUE TITLE
API interfaces should accept an lacp_mode to configure for port-channel members

### ISSUE THREAD

**Issue by jerearista** [arista-eosplus/rbeapi#58]
Update set_members() and add_member() to accept and lacp_mode.   This is so we can pass in the desired lacp_mode instead of the current lacp_mode when adding members and make Puppet idempotent when creating port-channels.

See https://github.com/arista-eosplus/ansible-eos/pull/69 and https://github.com/arista-eosplus/pyeapi/pull/47

**Comment by devrobo** [comment]
Changed set_members() and it will set all members to the array passed in and modify the lacp mode if specified. Adding lacp mode to add_member() instead of using the current setting creates a scenario where adding the member with the different lacp mode causes all the existing modes to have to be changed. I would think if adding members one at a time you would add the members and then update the lacp mode.

**Comment by jerearista** [comment]
Release Note:
set_members() now configures LACP mode when adding members to a port-channel
